-- ============================================================
-- Starter bank — 115 questions, ~4 months of runway.
--
-- genre = 'universal'  harmless private habits. The distribution engine:
--                      no stakes, instant answer, and the split genuinely
--                      surprises people. This is what gets filmed.
-- genre = 'workplace'  opinions about working life. Fewer of these, but they
--                      are where the dataset becomes worth something.
--
-- The scheduler runs a workplace question on Wednesdays and universal ones
-- the rest of the week (WORKPLACE_WEEKDAY in wrangler.toml).
--
-- Apply with:  wrangler d1 execute oqotd --remote --file=./seed.sql
-- ============================================================

INSERT OR IGNORE INTO questions (text, option_a, option_b, genre, category, status, source, predicted_a) VALUES

-- ---------- universal: getting dressed, washing, the bathroom ----------
('What goes on first?',                                                'Socks',              'Trousers',           'universal','dressing','approved','curated',58),
('Do you sit or stand to put your socks on?',                          'Sit down',           'Stand up',           'universal','dressing','approved','curated',62),
('Toilet roll hangs:',                                                 'Over the front',     'Under the back',     'universal','bathroom','approved','curated',71),
('Do you fold it or scrunch it?',                                      'Fold',               'Scrunch',            'universal','bathroom','approved','curated',56),
('In the shower, do you face the water or turn away?',                 'Face it',            'Turn away',          'universal','bathroom','approved','curated',47),
('Do you dry yourself inside the shower or outside?',                  'Inside',             'Outside',            'universal','bathroom','approved','curated',34),
('Toothbrush: wet it before the paste, or after?',                     'Before',             'After',              'universal','bathroom','approved','curated',52),
('Do you rinse from the tap or from a cup?',                           'The tap',            'A cup',              'universal','bathroom','approved','curated',66),
('Brush your teeth before or after breakfast?',                        'Before',             'After',              'universal','bathroom','approved','curated',48),
('Do you shower in the morning or at night?',                          'Morning',            'Night',              'universal','bathroom','approved','curated',61),
('Do you sleep with socks on?',                                        'Socks on',           'Socks off',          'universal','sleep','approved','curated',29),
('One leg out of the duvet?',                                          'One leg out',        'Fully covered',      'universal','sleep','approved','curated',54),
('Do you make the bed if you are leaving the house immediately?',      'Still make it',      'Leave it',           'universal','home','approved','curated',44),
('Same bath towel twice?',                                             'Reuse it',           'Fresh one',          'universal','home','approved','curated',73),
('Shoes off at someone else’s house without being asked?',             'Off automatically',  'Wait to be told',    'universal','home','approved','curated',67),

-- ---------- universal: food ----------
('Is a hot dog a sandwich?',                                           'Yes',                'No',                 'universal','food','approved','curated',31),
('Do you cut a sandwich diagonally or straight?',                      'Diagonally',         'Straight across',    'universal','food','approved','curated',59),
('Ketchup lives in:',                                                  'The fridge',         'The cupboard',       'universal','food','approved','curated',64),
('Do you keep bread in the fridge?',                                   'Yes',                'Never',              'universal','food','approved','curated',27),
('Pizza crust:',                                                       'Eat it',             'Leave it',           'universal','food','approved','curated',69),
('Do you eat pizza with your hands or a knife and fork?',              'Hands',              'Knife and fork',     'universal','food','approved','curated',74),
('Crisps: one at a time, or a handful?',                               'One at a time',      'Handful',            'universal','food','approved','curated',43),
('Do you eat the bottom of the ice cream cone?',                       'Yes',                'Bin it',             'universal','food','approved','curated',68),
('Banana: peel from the top or the bottom?',                           'Top',                'Bottom',             'universal','food','approved','curated',72),
('Do you butter the bread or the knife?',                              'Butter the bread',   'Load the knife',     'universal','food','approved','curated',61),
('Tea: milk in first or last?',                                        'Milk first',         'Milk last',          'universal','food','approved','curated',33),
('Do you eat a burger from the edge or the middle?',                   'Edge',               'Middle',             'universal','food','approved','curated',58),
('Do you finish everything on your plate?',                            'Always',             'Leave a bit',        'universal','food','approved','curated',63),
('Do you drink the last mouthful of milk from the carton?',            'Yes',                'Leave it',           'universal','food','approved','curated',41),
('Is cereal soup?',                                                    'Yes',                'No',                 'universal','food','approved','curated',26),

-- ---------- universal: small daily behaviour ----------
('Phone on the table:',                                                'Face down',          'Face up',            'universal','habits','approved','curated',66),
('Do you press the lift button again if it is already lit?',           'Press it again',     'Trust it',           'universal','habits','approved','curated',49),
('Do you count the stairs?',                                           'Sometimes',          'Never',              'universal','habits','approved','curated',37),
('Do you re-read a message immediately after sending it?',             'Every time',         'Never',              'universal','habits','approved','curated',64),
('Do you know your own phone number by heart?',                        'Yes',                'No',                 'universal','habits','approved','curated',57),
('Do you say “you’re welcome” or “no problem”?',                       'You’re welcome',     'No problem',         'universal','habits','approved','curated',46),
('Do you thank the bus driver?',                                       'Always',             'Never',              'universal','habits','approved','curated',59),
('Do you read the subtitles even in your own language?',              'Subtitles on',       'Subtitles off',      'universal','habits','approved','curated',53),
('Do you hear a voice in your head when you read?',                    'Yes',                'No',                 'universal','habits','approved','curated',71),
('Do you set an alarm you intend to snooze?',                          'Yes',                'One alarm only',     'universal','habits','approved','curated',58),
('Do you check the forecast or just look outside?',                     'Check the forecast','Look outside',       'universal','habits','approved','curated',54),
('Do you walk faster when someone is behind you?',                     'Yes',                'Same speed',         'universal','habits','approved','curated',62),
('Do you use the trolley coin return or bring your own coin?',         'Own coin',           'Whatever is there',  'universal','habits','approved','curated',38),
('Do you keep receipts?',                                             'Yes',                'Bin them',           'universal','habits','approved','curated',44),
('Do you close browser tabs or let them pile up?',                     'Close them',         'Let them pile',      'universal','habits','approved','curated',42),
('Do you charge your phone overnight?',                                'Overnight',          'During the day',     'universal','habits','approved','curated',68),
('Do you answer a number you do not recognise?',                       'Answer it',          'Let it ring',        'universal','habits','approved','curated',31),
('Do you listen to podcasts at normal speed?',                         'Normal speed',       'Sped up',            'universal','habits','approved','curated',55),
('Do you queue at the door before the plane starts boarding?',         'Stand up early',     'Stay seated',        'universal','travel','approved','curated',47),
('Window seat or aisle?',                                             'Window',             'Aisle',              'universal','travel','approved','curated',54),
('Do you pack the night before or the morning of?',                    'Night before',       'Morning of',         'universal','travel','approved','curated',65),
('Do you take the free hotel toiletries?',                             'Take them',          'Leave them',         'universal','travel','approved','curated',61),
('Do you clap when the plane lands?',                                  'Yes',                'Absolutely not',     'universal','travel','approved','curated',28),
('Do you unpack your suitcase the day you get home?',                  'Same day',           'It sits there',      'universal','travel','approved','curated',39),
('Do you sing in the car when someone else is in it?',                 'Sing anyway',        'Only alone',         'universal','habits','approved','curated',45),

-- ---------- workplace ----------
('Is “quick call?” with no context a threat?',                         'It’s a threat',      'Perfectly normal',   'workplace','comms','approved','curated',72),
('Reply-all thank-yous are:',                                          'Harmless',           'Criminal',           'workplace','comms','approved','curated',38),
('Camera on by default?',                                              'Camera on',          'Absolutely not',     'workplace','tools','approved','curated',34),
('Someone microwaves fish in the office kitchen.',                     'Say something',      'Suffer quietly',     'workplace','kitchen','approved','curated',41),
('Do you read the all-hands deck before the all-hands?',               'Yes',                'Never once',         'workplace','meetings','approved','curated',29),
('The meeting could have been an email. Do you say it out loud?',      'Say it',             'Just think it',      'workplace','meetings','approved','curated',31),
('Office fridge policy:',                                              'Label your food',    'Trust the system',   'workplace','kitchen','approved','curated',63),
('Worse deskmate:',                                                    'Loud typer',         'Loud chewer',        'workplace','space','approved','curated',26),
('Do you mute yourself to sigh?',                                      'Yes',                'No',                 'workplace','meetings','approved','curated',58),
('Is 9:01 late?',                                                      'It’s late',          'It’s 9-ish',         'workplace','hours','approved','curated',22),
('Pick one, forever:',                                                 'Free lunch daily',   'Leave an hour early','workplace','hours','approved','curated',44),
('Do you have a separate work voice?',                                  'Yes',                'This is my only voice','workplace','social','approved','curated',67),
('A colleague’s birthday and someone starts singing.',                 'Join in',            'Clap and look away', 'workplace','social','approved','curated',43),
('Would you take 10% less pay to never attend another meeting?',       'Take the cut',       'Keep the money',     'workplace','meetings','approved','curated',37),
('Last one out of the kitchen — must you run the dishwasher?',         'You must',           'Not your job',       'workplace','kitchen','approved','curated',61),
('Do you laugh at your manager’s jokes?',                              'Yes, always',        'I’ve stopped',       'workplace','managers','approved','curated',54),
('Eating lunch at your desk is:',                                      'Totally fine',       'Get up and leave',   'workplace','kitchen','approved','curated',52),
('Two weeks’ notice, or leave immediately with severance?',            'Work the notice',    'Take the money',     'workplace','career','approved','curated',33),
('Do you know what your CEO actually does all day?',                   'Yes',                'No idea',            'workplace','managers','approved','curated',24),
('Choose your poison:',                                                'Bad boss, great pay','Great boss, average pay','workplace','managers','approved','curated',28),
('Hot-desking is:',                                                    'A punishment',       'Fine, actually',     'workplace','space','approved','curated',66),
('Your emoji reactions are:',                                          'Sincere',            'Deeply ironic',      'workplace','comms','approved','curated',47),
('Unclaimed cake appears in the kitchen.',                             'Take a slice',       'Wait for permission','workplace','kitchen','approved','curated',48),
('Choose:',                                                            'Underpaid, unbothered','Well paid, always on','workplace','career','approved','curated',49),
('Do you take your full lunch break?',                                 'Every minute',       'What lunch break',   'workplace','hours','approved','curated',35),
('“Per my last email” is:',                                            'Passive aggressive', 'Simply efficient',   'workplace','comms','approved','curated',69),
('Is the office coffee drinkable?',                                    'It’s fine',          'I bring my own',     'workplace','kitchen','approved','curated',45),
('Ever blamed your connection for something else?',                    'Guilty',             'Never',              'workplace','tools','approved','curated',64),
('Which would you rather your team see?',                              'Your search history','Your private messages','workplace','tools','approved','curated',57),
('Do you clap at the end of a presentation?',                          'Yes',                'No',                 'workplace','meetings','approved','curated',56),
('Standing desks are:',                                                'Genuinely better',   'Performance art',    'workplace','space','approved','curated',53),
('Pick the week:',                                                     '4 days, no flexibility','5 days, fully flexible','workplace','hours','approved','curated',59),
('Calling your colleagues “family” is:',                               'A red flag',         'Kind of sweet',      'workplace','social','approved','curated',71),
('Does anyone read the notes you take in meetings?',                   'Someone does',       'Absolutely nobody',  'workplace','meetings','approved','curated',36),
('Camera on for a one-to-one is:',                                     'Mandatory',          'Optional',           'workplace','meetings','approved','curated',51),
('Would you rather have no manager, or no colleagues?',                'No manager',         'No colleagues',      'workplace','managers','approved','curated',62),
('Someone books a meeting over your lunch.',                           'Decline it',         'Move your lunch',    'workplace','meetings','approved','curated',42),
('A recruiter messages you while you are happy at work.',              'Always reply',        'Ignore it',          'workplace','career','approved','curated',58),
('Do you answer messages after hours?',                                'Yes',                'It can wait',        'workplace','hours','approved','curated',46),
('Is it acceptable to eat labelled food that is about to expire?',     'Never',              'Saving it, really',  'workplace','kitchen','approved','curated',77),
('Your manager makes an obvious mistake in front of the team.',        'Correct them there', 'Message them after', 'workplace','managers','approved','curated',21),
('Voice notes at work are:',                                           'Efficient',          'A war crime',        'workplace','comms','approved','curated',32),
('Would you rather present to 200 strangers or 6 senior leaders?',     '200 strangers',      '6 senior leaders',   'workplace','career','approved','curated',55),
('Small talk in the lift:',                                            'Required',           'Absolutely not',     'workplace','social','approved','curated',39),
('Someone puts a meeting in with no agenda.',                          'Ask for one',        'Just show up',       'workplace','meetings','approved','curated',44),
('Do you actually use your out-of-office reply properly?',             'Yes',                'I check anyway',     'workplace','hours','approved','curated',27),
('Is being “busy” a personality?',                                     'Yes',                'It’s just honest',   'workplace','social','approved','curated',65),
('Better: a boss who over-explains, or one who explains nothing?',     'Over-explains',      'Explains nothing',   'workplace','managers','approved','curated',74),
('Would you tell a colleague they are underpaid?',                     'Tell them',          'Stay out of it',     'workplace','career','approved','curated',59),
('Do you rehearse before you speak in a big meeting?',                 'Every time',         'Wing it',            'workplace','meetings','approved','curated',48),
('Open-plan offices are:',                                             'A mistake',          'Fine',               'workplace','space','approved','curated',73),
('A colleague takes credit for your idea in a meeting.',               'Say so immediately', 'Deal with it later', 'workplace','social','approved','curated',34),
('Do you pretend to understand the finance slides?',                   'Every time',         'I ask',              'workplace','meetings','approved','curated',61),
('Would you rather your calendar be public, or your salary?',          'Calendar',           'Salary',             'workplace','career','approved','curated',68),
('Someone eats at their desk during your one-to-one.',                 'Rude',               'Who cares',          'workplace','social','approved','curated',49),
('Do you have a colleague you would follow to another company?',       'Yes',                'Not one',            'workplace','career','approved','curated',63),
('“Let’s take this offline” means:',                                   'We will never discuss it','We will discuss it later','workplace','comms','approved','curated',57),
('Turning up early to a meeting is:',                                  'Basic respect',      'Slightly odd',       'workplace','meetings','approved','curated',52),
('Do you know your colleagues’ job titles?',                           'Most of them',       'Barely any',         'workplace','social','approved','curated',43);
